version: "3.9"
services:
  db:
    image: postgres:15-alpine
    networks: [appnet]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Comment this in ONLY if you want host access with psql
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks: [appnet]
    environment:
      # SQLAlchemy + psycopg3 driver prefix
      DB_URL: postgresql+psycopg://postgres:postgres@db:5432/postgres
      # If your app code reads DATABASE_URL instead, keep this too:
      # DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    image: nginx:stable-alpine
    depends_on:
      - api
    networks: [appnet]
    volumes:
      # mount pages and public as siblings (no overlap)
      - ./frontend/pages:/usr/share/nginx/site/pages:ro
      - ./frontend/public:/usr/share/nginx/site/public:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped


#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./letsencrypt:/etc/letsencrypt
#      - ./certbot:/var/www/certbot
#    entrypoint: /bin/sh

networks:
  appnet:

volumes:
  postgres_data:
