version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
